### ISSUE TITLE
Use winsock2.h to create TCP connection using static IP address

### ISSUE THREAD

**Issue by yook00627** [Meowster-s-Manual/Simple-Spider#1]
Create client TCP connection using winsock2.h library for Windows

**Comment by andrew-suh** [comment]
We have successfully created a working socket that sends and receives data to an ip address at port 80.

**Comment by andrew-suh** [comment]
#6 Linked as it is part of this issue

**Comment by andrew-suh** [comment]
[ ] #6

**Comment by andrew-suh** [comment]
- [x] #6 
- [x] #7

**Comment by andrew-suh** [comment]
This is done
